### ISSUE TITLE
Write the first principles of the community

### ISSUE THREAD

**Issue by Zen0x7** [sharepls/sharepls#3]
A community needs to define principles that keep the evil out of here.

**Comment by Zen0x7** [comment]
I propose the principle 

# Safely

This principle is about the **user**. We need protect their information and health.

**Comment by demency** [comment]
- [ ] Explain why safely is important
- [ ] Propose solution to safely problem of sharepls

**Comment by Zen0x7** [comment]
- [ ] Explain what means safely
- [ ] Expose related risks
- [ ] Propose solutions to warranty the safely

**Comment by Zen0x7** [comment]
Cerrado por cambios en la orientación del proyecto
